name: Prettify Markdown files and generate PDFs with pandoc

on:
  push:
    branches:
      - main
    paths:
      - "**/*.md"
      - "!README.md"

jobs:
  prettify:
    name: Prettify Markdown files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Prettify
        uses: creyD/prettier_action@v3.3
        with:
          prettier_options: --prose-wrap always --write *.md
          commit_message: Prettified .md files via action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  generate_pdfs:
    name: Compile Markdown files to PDF
    needs: prettify
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Create PDF folder and subfolders if needed
        run: |
          for dir in */; do
            mkdir -p pdfs/$dir
          done
      - name: Pandoc PDF compilation
        uses: docker://pandoc/latex:2.13
        with:
          entrypoint: /bin/sh
          args: >-
            -c "find . -iname '*.md' ! -name 'README.md' -type f
            -exec sh -c 'pandoc ${0} -o pdfs/${0%.md}.pdf' {} \;
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.10.0
        with:
          commit_message: Add new PDFs via action
          file_pattern: pdfs
